# Site settings
title: BioPhysCode
description: >
  Web portal for the biophyscode project.
#! `rake test` to check links
#! change Rakefile if you change baseurl
#! use empty instead of "/" to pass `rake test`
baseurl: ""
github_username:  biophyscode
highlighter: rouge
# build settings
markdown: kramdown
collections:
  posts:
    output: true
    permalink: /posts/:path.html
  articles:
    output: true
    permalink: /articles/:title.html
  test_reports:
    output: true
    permalink: /test_reports/:title.html
